### ISSUE TITLE
Error when calculating payslip for 2019

### ISSUE THREAD

**Issue by jumshudsultan** [ERPGO/goboostan#28]
We've got working time set for 2020 and I created a payslip for 2019 and faced with this error:

Xəta:
	Odoo Server Error

	Traceback (most recent call last):
	  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
	    result = request.dispatch()
	  File "/home/odoo/src/odoo/odoo/http.py", line 683, in dispatch
	    result = self._call_function(**self.params)
	  File "/home/odoo/src/odoo/odoo/http.py", line 359, in _call_function
	    return checked_call(self.db, *args, **kwargs)
	  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
	    return f(dbname, *args, **kwargs)
	  File "/home/odoo/src/odoo/odoo/http.py", line 347, in checked_call
	    result = self.endpoint(*a, **kw)
	  File "/home/odoo/src/odoo/odoo/http.py", line 912, in __call__
	    return self.method(*args, **kw)
	  File "/home/odoo/src/odoo/odoo/http.py", line 531, in response_wrap
	    response = f(*args, **kw)
	  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1322, in search_read
	    return self.do_search_read(model, fields, offset, limit, domain, sort)
	  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1341, in do_search_read
	    return Model.web_search_read(domain, fields, offset=offset, limit=limit, order=sort)
	  File "/home/odoo/src/odoo/addons/web/models/models.py", line 53, in web_search_read
	    records = self.search_read(domain, fields, offset=offset, limit=limit, order=order)
	  File "/home/odoo/src/odoo/odoo/models.py", line 4813, in search_read
	    result = records.read(fields)
	  File "/home/odoo/src/odoo/odoo/models.py", line 3016, in read
	    return self._read_format(fnames=fields, load=load)
	  File "/home/odoo/src/odoo/odoo/models.py", line 3036, in _read_format
	    vals[name] = convert(record[name], record, use_name_get)
	  File "/home/odoo/src/odoo/odoo/models.py", line 5640, in __getitem__
	    return self._fields[key].__get__(self, type(self))
	  File "/home/odoo/src/odoo/odoo/fields.py", line 987, in __get__
	    raise ValueError("Compute method failed to assign %s.%s" % (record, self.name))
	Exception

	The above exception was the direct cause of the following exception:

	Traceback (most recent call last):
	  File "/home/odoo/src/odoo/odoo/http.py", line 639, in _handle_exception
	    return super(JsonRequest, self)._handle_exception(exception)
	  File "/home/odoo/src/odoo/odoo/http.py", line 315, in _handle_exception
	    raise exception.with_traceback(None) from new_cause
	ValueError: Compute method failed to assign hr.payslip(1,).employee_worked_days

**Comment by jumshudsultan** [comment]
We need to think a solution for cut-off date payslips: e.g. when stepping into a new year, when should we update the global leaves???

**Comment by jumshudsultan** [comment]
the same error appeared for a batch of 2020 Jan

**Comment by jumshudsultan** [comment]
resolved
